/**
 * Setup Packet PDF Generator
 * 
 * Generates downloadable PDF versions of setup packets
 * for Google Business Profile, Meta, and QuickBooks integrations.
 */

import { GoogleBusinessPacket, MetaPacket, QuickBooksPacket } from "./setupPacketGenerator";

type SetupPacket = GoogleBusinessPacket | MetaPacket | QuickBooksPacket;

/**
 * Generate markdown content for a setup packet
 * This can be converted to PDF using manus-md-to-pdf
 */
export function generateSetupPacketMarkdown(packet: SetupPacket): string {
  const integrationTitles = {
    google_business: "Google Business Profile",
    meta: "Facebook & Instagram",
    quickbooks: "QuickBooks Online",
  };

  const title = integrationTitles[packet.integration];
  const businessName = packet.business.name;

  let md = `# ${title} Setup Packet
## ${businessName}

---

## Business Information

| Field | Value |
|-------|-------|
| **Business Name** | ${packet.business.name} |
| **Phone** | ${packet.business.phone} |
| **Website** | ${packet.business.website || "Not set"} |
| **Service Area** | ${packet.business.serviceArea.join(", ")} |
| **Hours** | ${packet.business.hours || "Not set"} |

---

## Brand Positioning

| Field | Value |
|-------|-------|
| **Tone** | ${packet.positioning.tone} |
| **Primary CTA** | ${packet.positioning.primaryCTA} |
| **One-Liner** | ${packet.positioning.oneLiner} |

---

## Services

`;

  packet.services.forEach((service, i) => {
    md += `### ${i + 1}. ${service.name}
${service.description}
${service.priceHint ? `*Price hint: ${service.priceHint}*` : ""}

`;
  });

  md += `---

## Setup Steps

`;

  packet.setupSteps.forEach((step) => {
    md += `### Step ${step.step}: ${step.title}
${step.instructions}
${step.deepLink ? `\n🔗 [Open Setup Page](${step.deepLink})` : ""}

`;
  });

  // Integration-specific content
  if (packet.integration === "google_business") {
    const specific = packet.specific;
    md += `---

## Google Business Profile Details

### Categories
- **Primary:** ${specific.primaryCategory}
- **Additional:** ${specific.additionalCategories.join(", ")}

### Business Description
> ${specific.description}

### Attributes
${specific.attributes.map(a => `- ${a}`).join("\n")}

### Photo Guidelines
${specific.photoGuidelines.map(g => `- ${g}`).join("\n")}

### Review Response Templates

**Positive Review:**
> ${specific.reviewResponseTemplates.positive}

**Neutral Review:**
> ${specific.reviewResponseTemplates.neutral}

**Negative Review:**
> ${specific.reviewResponseTemplates.negative}
`;
  } else if (packet.integration === "meta") {
    const specific = packet.specific;
    md += `---

## Facebook & Instagram Details

### Page Bio (255 chars max)
> ${specific.pageBio}

### About Section
> ${specific.aboutSection}

### CTA Button
- **Type:** ${specific.ctaButton.type}
- **Link:** ${specific.ctaButton.link}

### Pinned Post Draft
> ${specific.pinnedPostDraft}

### Image Specifications
- **Profile Image:** ${specific.profileImageSpec}
- **Cover Image:** ${specific.coverImageSpec}

### Posting Cadence
${specific.postingCadence}

### Tone Notes
${specific.toneNotes}

### Hashtag Strategy
${specific.hashtagStrategy.map(h => `#${h}`).join(" ")}
`;
  } else if (packet.integration === "quickbooks") {
    const specific = packet.specific;
    md += `---

## QuickBooks Online Details

### Customer Types
${specific.customerTypes.map(c => `- **${c.name}:** ${c.description}`).join("\n")}

### Service Items
| Name | Rate | Description |
|------|------|-------------|
${specific.serviceItems.map(s => `| ${s.name} | ${s.rate ? `$${s.rate}` : "TBD"} | ${s.description} |`).join("\n")}

### Invoice Template
- **Terms:** ${specific.invoiceTemplate.terms}
- **Due Date:** ${specific.invoiceTemplate.dueDate}
- **Notes:** ${specific.invoiceTemplate.notes}
- **Footer:** ${specific.invoiceTemplate.footer}

### Payment Terms
${specific.paymentTerms}

### Chart of Accounts Starter
${specific.chartOfAccountsStarter.map(a => `- **${a.name}** (${a.type}): ${a.description}`).join("\n")}

### Tax Categories
${specific.taxCategories.map(t => `- **${t.name}:** ${t.rate ? `${t.rate}%` : "Variable"}`).join("\n")}
`;
  }

  md += `
---

## Assets Needed

| Item | Priority | Notes |
|------|----------|-------|
${packet.assetsNeeded.map(a => `| ${a.item} | ${a.priority.toUpperCase()} | ${a.note} |`).join("\n")}

---

*Generated by LaunchBase on ${new Date().toLocaleDateString()}*
`;

  return md;
}

/**
 * Generate a combined PDF with all setup packets
 */
export function generateAllPacketsMarkdown(packets: {
  google?: GoogleBusinessPacket;
  meta?: MetaPacket;
  quickbooks?: QuickBooksPacket;
}, businessName: string): string {
  let md = `# LaunchBase Setup Packets
## ${businessName}

This document contains all the information you need to set up your business integrations.

---

`;

  if (packets.google) {
    md += generateSetupPacketMarkdown(packets.google);
    md += "\n\n---\n\n";
  }

  if (packets.meta) {
    md += generateSetupPacketMarkdown(packets.meta);
    md += "\n\n---\n\n";
  }

  if (packets.quickbooks) {
    md += generateSetupPacketMarkdown(packets.quickbooks);
  }

  return md;
}
